### ISSUE TITLE
Make the API an injectable service

### ISSUE THREAD

**Issue by chrillewoodz** [KensingtonTech/ngx-panzoom#37]
Hi, great module.

However, I find it very awkward and wonky to work with the API.
It should be an injectable service to make it easier to manage and get hold of.

**Comment by KensingtonTech** [comment]
Sorry, not going to do it.

**Comment by chrillewoodz** [comment]
@KensingtonTech Mind telling me why? It becomes a problem when you have to share the api around, would be a lot easier with a service.

**Comment by KensingtonTech** [comment]
@chrillewoodz I don't mind.  When I was porting this over from Martin Vindahl Olsen's AngularJS version, there was a PanZoom service.  I deliberately eliminated it, as some debugging indicated that adding a service, any service, significantly increased the memory footprint of an Angular app, which I thought excessive for what it was doing.  Admittedly, that was a few years ago (Angular 2/4 days), so I don't know how big of an issue that is today.  While it may be a bit "wonky", as you describe it, it requires no esoteric component references on the part of the developer to utilise the API.  All you need to get at the API is the observable from the config object, which you, yourself create, and you can pass that around, or even the API reference it returns, until your heart's content.  It's a different approach than most libraries, I grant, but I frankly sometimes don't like the way other libraries go about things.

Even if it were something I wanted to do, it would require time and effort on my part to achieve. This library is something I put a lot of time in now and derive almost no personal benefit.  I first ported it only for the reason there was nothing else like it for Angular, and I needed something like it for another, now defunct project.  After some time it occurred to me that I should give back to the community and publish it, as Mr. Olsen had so graciously done with his original project.  So I did, but it was never my intention to do a great deal of further development beyond maintaining it for future versions.  It turns out that I've already put much more effort into it than I had ever planned to do.  Without deriving any financial benefit from the project, it's hard to justify expending cycles on much more than bug fixes or the occasional small new feature.

I hope that answers your question.
